id: PA0C4F688
initial_creation_type: input
source_metadata:
  title: Drikung Kyobpa Jikten Sumgön
  language: bo
  description: 'Texts by and about Drikung Kyobpa Jikten Sumgön (''bri gung skyob
    pa ''jig rten gsum mgon, 1143–1217), founder of the Drikung Kagyü tradition:'
  volume:
    81662a452bdc491f99f4cf97cb4a7b04:
      title: In Praise of Padmākara, the Great Guru of Uḍḍiyāna
      parent: Praise
    98ac5c3058424b6dbd36e78ab4259185:
      title: 'Praise of the Buddha: With Skilful Means & Compassion...'
      parent: Praise
    53e3fa04c368411ea7c1bb0a3b5de95e:
      title: Verses in Praise of the Protector Akṣobhya
      parent: Praise
    43a0fa8192ca42edbbf5242ef14e04e0:
      title: 'Prayer to Tārā: A Sevenfold Supplication for Protection'
      parent: Prayers
created_at: '2022-02-28T23:03:51.358582'
last_modified_at: '2022-02-28T23:03:51.358584'
